name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
        env:
          JWT_SECRET_KEY: sEcReTKeI12345
          MONGODB_URL: mongodb+srv://oriolraventosc:oriolraventosc@cluster0.ltojm2e.mongodb.net/scanner-api
          REACT_APP_URL_MOCK: https://ecommerce-api-n953.onrender.com/
